
namespace SuperMarket_Inventory_System
{
    partial class Login
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Utilities.BunifuPages.BunifuAnimatorNS.Animation animation1 = new Utilities.BunifuPages.BunifuAnimatorNS.Animation();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Login));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            this.LoginDock = new Bunifu.UI.WinForms.BunifuFormDock();
            this.LoginGradientPanel = new Bunifu.Framework.UI.BunifuGradientPanel();
            this.btn_SignInPage = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_SignUpPage = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.label3 = new System.Windows.Forms.Label();
            this.LoginPages = new Bunifu.UI.WinForms.BunifuPages();
            this.SignIn = new System.Windows.Forms.TabPage();
            this.btn_SignIn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txt_SignInPassword = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txt_SignInEmail = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.SignUp = new System.Windows.Forms.TabPage();
            this.txt_SignUpConfirmPassword = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txt_SignUpPassword = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.btn_SignUp = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txt_SignUpEmail = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.txt_SignUpName = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.LoginGradientPanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.LoginPages.SuspendLayout();
            this.SignIn.SuspendLayout();
            this.SignUp.SuspendLayout();
            this.SuspendLayout();
            // 
            // LoginDock
            // 
            this.LoginDock.AllowFormDragging = true;
            this.LoginDock.AllowFormDropShadow = true;
            this.LoginDock.AllowFormResizing = false;
            this.LoginDock.AllowHidingBottomRegion = true;
            this.LoginDock.AllowOpacityChangesWhileDragging = false;
            this.LoginDock.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.LoginDock.BorderOptions.BottomBorder.BorderThickness = 1;
            this.LoginDock.BorderOptions.BottomBorder.ShowBorder = true;
            this.LoginDock.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.LoginDock.BorderOptions.LeftBorder.BorderThickness = 1;
            this.LoginDock.BorderOptions.LeftBorder.ShowBorder = true;
            this.LoginDock.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.LoginDock.BorderOptions.RightBorder.BorderThickness = 1;
            this.LoginDock.BorderOptions.RightBorder.ShowBorder = true;
            this.LoginDock.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.LoginDock.BorderOptions.TopBorder.BorderThickness = 1;
            this.LoginDock.BorderOptions.TopBorder.ShowBorder = true;
            this.LoginDock.ContainerControl = this;
            this.LoginDock.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.LoginDock.DockingIndicatorsOpacity = 0.5D;
            this.LoginDock.DockingOptions.DockAll = true;
            this.LoginDock.DockingOptions.DockBottomLeft = true;
            this.LoginDock.DockingOptions.DockBottomRight = true;
            this.LoginDock.DockingOptions.DockFullScreen = true;
            this.LoginDock.DockingOptions.DockLeft = true;
            this.LoginDock.DockingOptions.DockRight = true;
            this.LoginDock.DockingOptions.DockTopLeft = true;
            this.LoginDock.DockingOptions.DockTopRight = true;
            this.LoginDock.FormDraggingOpacity = 0.9D;
            this.LoginDock.ParentForm = this;
            this.LoginDock.ShowCursorChanges = true;
            this.LoginDock.ShowDockingIndicators = false;
            this.LoginDock.TitleBarOptions.AllowFormDragging = true;
            this.LoginDock.TitleBarOptions.BunifuFormDock = this.LoginDock;
            this.LoginDock.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.LoginDock.TitleBarOptions.TitleBarControl = null;
            this.LoginDock.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // LoginGradientPanel
            // 
            this.LoginGradientPanel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("LoginGradientPanel.BackgroundImage")));
            this.LoginGradientPanel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.LoginGradientPanel.Controls.Add(this.btn_SignInPage);
            this.LoginGradientPanel.Controls.Add(this.btn_SignUpPage);
            this.LoginGradientPanel.Controls.Add(this.label2);
            this.LoginGradientPanel.Controls.Add(this.label1);
            this.LoginGradientPanel.Controls.Add(this.pictureBox1);
            this.LoginGradientPanel.Dock = System.Windows.Forms.DockStyle.Left;
            this.LoginGradientPanel.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(213)))), ((int)(((byte)(237)))));
            this.LoginGradientPanel.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(147)))), ((int)(((byte)(176)))));
            this.LoginGradientPanel.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(33)))), ((int)(((byte)(147)))), ((int)(((byte)(176)))));
            this.LoginGradientPanel.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(213)))), ((int)(((byte)(237)))));
            this.LoginGradientPanel.Location = new System.Drawing.Point(0, 0);
            this.LoginGradientPanel.Name = "LoginGradientPanel";
            this.LoginGradientPanel.Quality = 10;
            this.LoginGradientPanel.Size = new System.Drawing.Size(457, 544);
            this.LoginGradientPanel.TabIndex = 0;
            // 
            // btn_SignInPage
            // 
            this.btn_SignInPage.AllowToggling = false;
            this.btn_SignInPage.AnimationSpeed = 200;
            this.btn_SignInPage.AutoGenerateColors = false;
            this.btn_SignInPage.BackColor = System.Drawing.Color.Transparent;
            this.btn_SignInPage.BackColor1 = System.Drawing.Color.Transparent;
            this.btn_SignInPage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_SignInPage.BackgroundImage")));
            this.btn_SignInPage.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_SignInPage.ButtonText = "SIGN IN";
            this.btn_SignInPage.ButtonTextMarginLeft = 0;
            this.btn_SignInPage.ColorContrastOnClick = 45;
            this.btn_SignInPage.ColorContrastOnHover = 45;
            this.btn_SignInPage.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btn_SignInPage.CustomizableEdges = borderEdges3;
            this.btn_SignInPage.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_SignInPage.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_SignInPage.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_SignInPage.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_SignInPage.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_SignInPage.Font = new System.Drawing.Font("Montserrat SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btn_SignInPage.ForeColor = System.Drawing.Color.White;
            this.btn_SignInPage.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_SignInPage.IconMarginLeft = 11;
            this.btn_SignInPage.IconPadding = 10;
            this.btn_SignInPage.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_SignInPage.IdleBorderColor = System.Drawing.Color.White;
            this.btn_SignInPage.IdleBorderRadius = 35;
            this.btn_SignInPage.IdleBorderThickness = 2;
            this.btn_SignInPage.IdleFillColor = System.Drawing.Color.Transparent;
            this.btn_SignInPage.IdleIconLeftImage = null;
            this.btn_SignInPage.IdleIconRightImage = null;
            this.btn_SignInPage.IndicateFocus = false;
            this.btn_SignInPage.Location = new System.Drawing.Point(72, 392);
            this.btn_SignInPage.Name = "btn_SignInPage";
            stateProperties29.BorderColor = System.Drawing.Color.White;
            stateProperties29.BorderRadius = 35;
            stateProperties29.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties29.BorderThickness = 2;
            stateProperties29.FillColor = System.Drawing.Color.White;
            stateProperties29.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(213)))), ((int)(((byte)(237)))));
            stateProperties29.IconLeftImage = null;
            stateProperties29.IconRightImage = null;
            this.btn_SignInPage.onHoverState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties30.BorderRadius = 35;
            stateProperties30.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties30.BorderThickness = 2;
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties30.ForeColor = System.Drawing.Color.White;
            stateProperties30.IconLeftImage = null;
            stateProperties30.IconRightImage = null;
            this.btn_SignInPage.OnPressedState = stateProperties30;
            this.btn_SignInPage.Size = new System.Drawing.Size(129, 45);
            this.btn_SignInPage.TabIndex = 6;
            this.btn_SignInPage.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_SignInPage.TextMarginLeft = 0;
            this.btn_SignInPage.UseDefaultRadiusAndThickness = true;
            this.btn_SignInPage.Click += new System.EventHandler(this.btn_SignInPage_Click);
            // 
            // btn_SignUpPage
            // 
            this.btn_SignUpPage.AllowToggling = false;
            this.btn_SignUpPage.AnimationSpeed = 200;
            this.btn_SignUpPage.AutoGenerateColors = false;
            this.btn_SignUpPage.BackColor = System.Drawing.Color.Transparent;
            this.btn_SignUpPage.BackColor1 = System.Drawing.Color.Transparent;
            this.btn_SignUpPage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_SignUpPage.BackgroundImage")));
            this.btn_SignUpPage.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_SignUpPage.ButtonText = "SIGN UP";
            this.btn_SignUpPage.ButtonTextMarginLeft = 0;
            this.btn_SignUpPage.ColorContrastOnClick = 45;
            this.btn_SignUpPage.ColorContrastOnHover = 45;
            this.btn_SignUpPage.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btn_SignUpPage.CustomizableEdges = borderEdges4;
            this.btn_SignUpPage.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_SignUpPage.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_SignUpPage.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_SignUpPage.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_SignUpPage.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_SignUpPage.Font = new System.Drawing.Font("Montserrat SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btn_SignUpPage.ForeColor = System.Drawing.Color.White;
            this.btn_SignUpPage.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_SignUpPage.IconMarginLeft = 11;
            this.btn_SignUpPage.IconPadding = 10;
            this.btn_SignUpPage.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_SignUpPage.IdleBorderColor = System.Drawing.Color.White;
            this.btn_SignUpPage.IdleBorderRadius = 35;
            this.btn_SignUpPage.IdleBorderThickness = 2;
            this.btn_SignUpPage.IdleFillColor = System.Drawing.Color.Transparent;
            this.btn_SignUpPage.IdleIconLeftImage = null;
            this.btn_SignUpPage.IdleIconRightImage = null;
            this.btn_SignUpPage.IndicateFocus = false;
            this.btn_SignUpPage.Location = new System.Drawing.Point(232, 392);
            this.btn_SignUpPage.Name = "btn_SignUpPage";
            stateProperties31.BorderColor = System.Drawing.Color.White;
            stateProperties31.BorderRadius = 35;
            stateProperties31.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties31.BorderThickness = 2;
            stateProperties31.FillColor = System.Drawing.Color.White;
            stateProperties31.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(213)))), ((int)(((byte)(237)))));
            stateProperties31.IconLeftImage = null;
            stateProperties31.IconRightImage = null;
            this.btn_SignUpPage.onHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.White;
            stateProperties32.BorderRadius = 35;
            stateProperties32.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties32.BorderThickness = 2;
            stateProperties32.FillColor = System.Drawing.Color.Transparent;
            stateProperties32.ForeColor = System.Drawing.Color.White;
            stateProperties32.IconLeftImage = null;
            stateProperties32.IconRightImage = null;
            this.btn_SignUpPage.OnPressedState = stateProperties32;
            this.btn_SignUpPage.Size = new System.Drawing.Size(129, 45);
            this.btn_SignUpPage.TabIndex = 5;
            this.btn_SignUpPage.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_SignUpPage.TextMarginLeft = 0;
            this.btn_SignUpPage.UseDefaultRadiusAndThickness = true;
            this.btn_SignUpPage.Click += new System.EventHandler(this.btn_SignUpPage_Click_1);
            // 
            // label2
            // 
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Font = new System.Drawing.Font("Montserrat", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(27, 244);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(402, 197);
            this.label2.TabIndex = 3;
            this.label2.Text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor in" +
    "cididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam";
            this.label2.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Montserrat", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(74, 178);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(304, 44);
            this.label1.TabIndex = 2;
            this.label1.Text = "WELCOME BACK";
            this.label1.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(158, 39);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(130, 120);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 1;
            this.pictureBox1.TabStop = false;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Montserrat", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(213)))), ((int)(((byte)(237)))));
            this.label3.Location = new System.Drawing.Point(68, 35);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(388, 44);
            this.label3.TabIndex = 7;
            this.label3.Text = "Login to your account";
            this.label3.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // LoginPages
            // 
            this.LoginPages.Alignment = System.Windows.Forms.TabAlignment.Bottom;
            this.LoginPages.AllowTransitions = true;
            this.LoginPages.Controls.Add(this.SignIn);
            this.LoginPages.Controls.Add(this.SignUp);
            this.LoginPages.Location = new System.Drawing.Point(463, 0);
            this.LoginPages.Multiline = true;
            this.LoginPages.Name = "LoginPages";
            this.LoginPages.Page = this.SignUp;
            this.LoginPages.PageIndex = 1;
            this.LoginPages.PageName = "SignUp";
            this.LoginPages.PageTitle = "SignUp";
            this.LoginPages.SelectedIndex = 0;
            this.LoginPages.Size = new System.Drawing.Size(526, 544);
            this.LoginPages.TabIndex = 1;
            animation1.AnimateOnlyDifferences = true;
            animation1.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.BlindCoeff")));
            animation1.LeafCoeff = 0F;
            animation1.MaxTime = 1F;
            animation1.MinTime = 0F;
            animation1.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicCoeff")));
            animation1.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicShift")));
            animation1.MosaicSize = 0;
            animation1.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
            animation1.RotateCoeff = 0F;
            animation1.RotateLimit = 0F;
            animation1.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.ScaleCoeff")));
            animation1.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.SlideCoeff")));
            animation1.TimeCoeff = 0F;
            animation1.TransparencyCoeff = 1F;
            this.LoginPages.Transition = animation1;
            this.LoginPages.TransitionType = Utilities.BunifuPages.BunifuAnimatorNS.AnimationType.Transparent;
            // 
            // SignIn
            // 
            this.SignIn.Controls.Add(this.btn_SignIn);
            this.SignIn.Controls.Add(this.txt_SignInPassword);
            this.SignIn.Controls.Add(this.txt_SignInEmail);
            this.SignIn.Controls.Add(this.label3);
            this.SignIn.Location = new System.Drawing.Point(4, 4);
            this.SignIn.Name = "SignIn";
            this.SignIn.Padding = new System.Windows.Forms.Padding(3);
            this.SignIn.Size = new System.Drawing.Size(518, 518);
            this.SignIn.TabIndex = 0;
            this.SignIn.Text = "SignIn";
            this.SignIn.UseVisualStyleBackColor = true;
            // 
            // btn_SignIn
            // 
            this.btn_SignIn.AllowToggling = false;
            this.btn_SignIn.AnimationSpeed = 200;
            this.btn_SignIn.AutoGenerateColors = false;
            this.btn_SignIn.BackColor = System.Drawing.Color.Transparent;
            this.btn_SignIn.BackColor1 = System.Drawing.Color.Transparent;
            this.btn_SignIn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_SignIn.BackgroundImage")));
            this.btn_SignIn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_SignIn.ButtonText = "SIGN IN";
            this.btn_SignIn.ButtonTextMarginLeft = 0;
            this.btn_SignIn.ColorContrastOnClick = 45;
            this.btn_SignIn.ColorContrastOnHover = 45;
            this.btn_SignIn.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn_SignIn.CustomizableEdges = borderEdges1;
            this.btn_SignIn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_SignIn.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_SignIn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_SignIn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_SignIn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_SignIn.Font = new System.Drawing.Font("Montserrat SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btn_SignIn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(213)))), ((int)(((byte)(237)))));
            this.btn_SignIn.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_SignIn.IconMarginLeft = 11;
            this.btn_SignIn.IconPadding = 10;
            this.btn_SignIn.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_SignIn.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(213)))), ((int)(((byte)(237)))));
            this.btn_SignIn.IdleBorderRadius = 35;
            this.btn_SignIn.IdleBorderThickness = 2;
            this.btn_SignIn.IdleFillColor = System.Drawing.Color.Transparent;
            this.btn_SignIn.IdleIconLeftImage = null;
            this.btn_SignIn.IdleIconRightImage = null;
            this.btn_SignIn.IndicateFocus = false;
            this.btn_SignIn.Location = new System.Drawing.Point(300, 277);
            this.btn_SignIn.Name = "btn_SignIn";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(213)))), ((int)(((byte)(237)))));
            stateProperties1.BorderRadius = 35;
            stateProperties1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties1.BorderThickness = 2;
            stateProperties1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(213)))), ((int)(((byte)(237)))));
            stateProperties1.ForeColor = System.Drawing.Color.White;
            stateProperties1.IconLeftImage = null;
            stateProperties1.IconRightImage = null;
            this.btn_SignIn.onHoverState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(213)))), ((int)(((byte)(237)))));
            stateProperties2.BorderRadius = 35;
            stateProperties2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties2.BorderThickness = 2;
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(213)))), ((int)(((byte)(237)))));
            stateProperties2.IconLeftImage = null;
            stateProperties2.IconRightImage = null;
            this.btn_SignIn.OnPressedState = stateProperties2;
            this.btn_SignIn.Size = new System.Drawing.Size(166, 45);
            this.btn_SignIn.TabIndex = 7;
            this.btn_SignIn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_SignIn.TextMarginLeft = 0;
            this.btn_SignIn.UseDefaultRadiusAndThickness = true;
            this.btn_SignIn.Click += new System.EventHandler(this.btn_SignIn_Click);
            // 
            // txt_SignInPassword
            // 
            this.txt_SignInPassword.AcceptsReturn = false;
            this.txt_SignInPassword.AcceptsTab = false;
            this.txt_SignInPassword.AnimationSpeed = 200;
            this.txt_SignInPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_SignInPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_SignInPassword.BackColor = System.Drawing.Color.Transparent;
            this.txt_SignInPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_SignInPassword.BackgroundImage")));
            this.txt_SignInPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_SignInPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txt_SignInPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_SignInPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_SignInPassword.BorderRadius = 1;
            this.txt_SignInPassword.BorderThickness = 1;
            this.txt_SignInPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_SignInPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SignInPassword.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txt_SignInPassword.DefaultText = "";
            this.txt_SignInPassword.FillColor = System.Drawing.Color.White;
            this.txt_SignInPassword.HideSelection = true;
            this.txt_SignInPassword.IconLeft = ((System.Drawing.Image)(resources.GetObject("txt_SignInPassword.IconLeft")));
            this.txt_SignInPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SignInPassword.IconPadding = 10;
            this.txt_SignInPassword.IconRight = null;
            this.txt_SignInPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SignInPassword.Lines = new string[0];
            this.txt_SignInPassword.Location = new System.Drawing.Point(53, 207);
            this.txt_SignInPassword.MaxLength = 32767;
            this.txt_SignInPassword.MinimumSize = new System.Drawing.Size(100, 35);
            this.txt_SignInPassword.Modified = false;
            this.txt_SignInPassword.Multiline = false;
            this.txt_SignInPassword.Name = "txt_SignInPassword";
            stateProperties3.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SignInPassword.OnActiveState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Empty;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_SignInPassword.OnDisabledState = stateProperties4;
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SignInPassword.OnHoverState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Silver;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SignInPassword.OnIdleState = stateProperties6;
            this.txt_SignInPassword.PasswordChar = '\0';
            this.txt_SignInPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_SignInPassword.PlaceholderText = "Enter password";
            this.txt_SignInPassword.ReadOnly = false;
            this.txt_SignInPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_SignInPassword.SelectedText = "";
            this.txt_SignInPassword.SelectionLength = 0;
            this.txt_SignInPassword.SelectionStart = 0;
            this.txt_SignInPassword.ShortcutsEnabled = true;
            this.txt_SignInPassword.Size = new System.Drawing.Size(413, 44);
            this.txt_SignInPassword.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txt_SignInPassword.TabIndex = 9;
            this.txt_SignInPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_SignInPassword.TextMarginBottom = 0;
            this.txt_SignInPassword.TextMarginLeft = 5;
            this.txt_SignInPassword.TextMarginTop = 0;
            this.txt_SignInPassword.TextPlaceholder = "Enter password";
            this.txt_SignInPassword.UseSystemPasswordChar = false;
            this.txt_SignInPassword.WordWrap = true;
            this.txt_SignInPassword.KeyUp += new System.Windows.Forms.KeyEventHandler(this.txt_SignInPassword_KeyUp);
            // 
            // txt_SignInEmail
            // 
            this.txt_SignInEmail.AcceptsReturn = false;
            this.txt_SignInEmail.AcceptsTab = false;
            this.txt_SignInEmail.AnimationSpeed = 200;
            this.txt_SignInEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_SignInEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_SignInEmail.BackColor = System.Drawing.Color.Transparent;
            this.txt_SignInEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_SignInEmail.BackgroundImage")));
            this.txt_SignInEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_SignInEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txt_SignInEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_SignInEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_SignInEmail.BorderRadius = 1;
            this.txt_SignInEmail.BorderThickness = 1;
            this.txt_SignInEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_SignInEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SignInEmail.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txt_SignInEmail.DefaultText = "";
            this.txt_SignInEmail.FillColor = System.Drawing.Color.White;
            this.txt_SignInEmail.HideSelection = true;
            this.txt_SignInEmail.IconLeft = ((System.Drawing.Image)(resources.GetObject("txt_SignInEmail.IconLeft")));
            this.txt_SignInEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SignInEmail.IconPadding = 10;
            this.txt_SignInEmail.IconRight = null;
            this.txt_SignInEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SignInEmail.Lines = new string[0];
            this.txt_SignInEmail.Location = new System.Drawing.Point(53, 133);
            this.txt_SignInEmail.MaxLength = 32767;
            this.txt_SignInEmail.MinimumSize = new System.Drawing.Size(100, 35);
            this.txt_SignInEmail.Modified = false;
            this.txt_SignInEmail.Multiline = false;
            this.txt_SignInEmail.Name = "txt_SignInEmail";
            stateProperties7.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SignInEmail.OnActiveState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Empty;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_SignInEmail.OnDisabledState = stateProperties8;
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SignInEmail.OnHoverState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Silver;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SignInEmail.OnIdleState = stateProperties10;
            this.txt_SignInEmail.PasswordChar = '\0';
            this.txt_SignInEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_SignInEmail.PlaceholderText = "Enter email";
            this.txt_SignInEmail.ReadOnly = false;
            this.txt_SignInEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_SignInEmail.SelectedText = "";
            this.txt_SignInEmail.SelectionLength = 0;
            this.txt_SignInEmail.SelectionStart = 0;
            this.txt_SignInEmail.ShortcutsEnabled = true;
            this.txt_SignInEmail.Size = new System.Drawing.Size(413, 44);
            this.txt_SignInEmail.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txt_SignInEmail.TabIndex = 8;
            this.txt_SignInEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_SignInEmail.TextMarginBottom = 0;
            this.txt_SignInEmail.TextMarginLeft = 5;
            this.txt_SignInEmail.TextMarginTop = 0;
            this.txt_SignInEmail.TextPlaceholder = "Enter email";
            this.txt_SignInEmail.UseSystemPasswordChar = false;
            this.txt_SignInEmail.WordWrap = true;
            // 
            // SignUp
            // 
            this.SignUp.Controls.Add(this.txt_SignUpConfirmPassword);
            this.SignUp.Controls.Add(this.txt_SignUpPassword);
            this.SignUp.Controls.Add(this.btn_SignUp);
            this.SignUp.Controls.Add(this.txt_SignUpEmail);
            this.SignUp.Controls.Add(this.txt_SignUpName);
            this.SignUp.Controls.Add(this.label4);
            this.SignUp.Location = new System.Drawing.Point(4, 4);
            this.SignUp.Name = "SignUp";
            this.SignUp.Padding = new System.Windows.Forms.Padding(3);
            this.SignUp.Size = new System.Drawing.Size(518, 518);
            this.SignUp.TabIndex = 1;
            this.SignUp.Text = "SignUp";
            this.SignUp.UseVisualStyleBackColor = true;
            // 
            // txt_SignUpConfirmPassword
            // 
            this.txt_SignUpConfirmPassword.AcceptsReturn = false;
            this.txt_SignUpConfirmPassword.AcceptsTab = false;
            this.txt_SignUpConfirmPassword.AnimationSpeed = 200;
            this.txt_SignUpConfirmPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_SignUpConfirmPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_SignUpConfirmPassword.BackColor = System.Drawing.Color.Transparent;
            this.txt_SignUpConfirmPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_SignUpConfirmPassword.BackgroundImage")));
            this.txt_SignUpConfirmPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_SignUpConfirmPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txt_SignUpConfirmPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_SignUpConfirmPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_SignUpConfirmPassword.BorderRadius = 1;
            this.txt_SignUpConfirmPassword.BorderThickness = 1;
            this.txt_SignUpConfirmPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_SignUpConfirmPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SignUpConfirmPassword.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txt_SignUpConfirmPassword.DefaultText = "";
            this.txt_SignUpConfirmPassword.FillColor = System.Drawing.Color.White;
            this.txt_SignUpConfirmPassword.HideSelection = true;
            this.txt_SignUpConfirmPassword.IconLeft = ((System.Drawing.Image)(resources.GetObject("txt_SignUpConfirmPassword.IconLeft")));
            this.txt_SignUpConfirmPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SignUpConfirmPassword.IconPadding = 10;
            this.txt_SignUpConfirmPassword.IconRight = null;
            this.txt_SignUpConfirmPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SignUpConfirmPassword.Lines = new string[0];
            this.txt_SignUpConfirmPassword.Location = new System.Drawing.Point(53, 355);
            this.txt_SignUpConfirmPassword.MaxLength = 32767;
            this.txt_SignUpConfirmPassword.MinimumSize = new System.Drawing.Size(100, 35);
            this.txt_SignUpConfirmPassword.Modified = false;
            this.txt_SignUpConfirmPassword.Multiline = false;
            this.txt_SignUpConfirmPassword.Name = "txt_SignUpConfirmPassword";
            stateProperties11.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SignUpConfirmPassword.OnActiveState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Empty;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_SignUpConfirmPassword.OnDisabledState = stateProperties12;
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SignUpConfirmPassword.OnHoverState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Silver;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SignUpConfirmPassword.OnIdleState = stateProperties14;
            this.txt_SignUpConfirmPassword.PasswordChar = '\0';
            this.txt_SignUpConfirmPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_SignUpConfirmPassword.PlaceholderText = "Confirm password";
            this.txt_SignUpConfirmPassword.ReadOnly = false;
            this.txt_SignUpConfirmPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_SignUpConfirmPassword.SelectedText = "";
            this.txt_SignUpConfirmPassword.SelectionLength = 0;
            this.txt_SignUpConfirmPassword.SelectionStart = 0;
            this.txt_SignUpConfirmPassword.ShortcutsEnabled = true;
            this.txt_SignUpConfirmPassword.Size = new System.Drawing.Size(413, 44);
            this.txt_SignUpConfirmPassword.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txt_SignUpConfirmPassword.TabIndex = 17;
            this.txt_SignUpConfirmPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_SignUpConfirmPassword.TextMarginBottom = 0;
            this.txt_SignUpConfirmPassword.TextMarginLeft = 5;
            this.txt_SignUpConfirmPassword.TextMarginTop = 0;
            this.txt_SignUpConfirmPassword.TextPlaceholder = "Confirm password";
            this.txt_SignUpConfirmPassword.UseSystemPasswordChar = false;
            this.txt_SignUpConfirmPassword.WordWrap = true;
            this.txt_SignUpConfirmPassword.KeyUp += new System.Windows.Forms.KeyEventHandler(this.txt_SignUpConfirmPassword_KeyUp);
            // 
            // txt_SignUpPassword
            // 
            this.txt_SignUpPassword.AcceptsReturn = false;
            this.txt_SignUpPassword.AcceptsTab = false;
            this.txt_SignUpPassword.AnimationSpeed = 200;
            this.txt_SignUpPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_SignUpPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_SignUpPassword.BackColor = System.Drawing.Color.Transparent;
            this.txt_SignUpPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_SignUpPassword.BackgroundImage")));
            this.txt_SignUpPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_SignUpPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txt_SignUpPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_SignUpPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_SignUpPassword.BorderRadius = 1;
            this.txt_SignUpPassword.BorderThickness = 1;
            this.txt_SignUpPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_SignUpPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SignUpPassword.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txt_SignUpPassword.DefaultText = "";
            this.txt_SignUpPassword.FillColor = System.Drawing.Color.White;
            this.txt_SignUpPassword.HideSelection = true;
            this.txt_SignUpPassword.IconLeft = ((System.Drawing.Image)(resources.GetObject("txt_SignUpPassword.IconLeft")));
            this.txt_SignUpPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SignUpPassword.IconPadding = 10;
            this.txt_SignUpPassword.IconRight = null;
            this.txt_SignUpPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SignUpPassword.Lines = new string[0];
            this.txt_SignUpPassword.Location = new System.Drawing.Point(53, 281);
            this.txt_SignUpPassword.MaxLength = 32767;
            this.txt_SignUpPassword.MinimumSize = new System.Drawing.Size(100, 35);
            this.txt_SignUpPassword.Modified = false;
            this.txt_SignUpPassword.Multiline = false;
            this.txt_SignUpPassword.Name = "txt_SignUpPassword";
            stateProperties15.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SignUpPassword.OnActiveState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Empty;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_SignUpPassword.OnDisabledState = stateProperties16;
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SignUpPassword.OnHoverState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Silver;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SignUpPassword.OnIdleState = stateProperties18;
            this.txt_SignUpPassword.PasswordChar = '\0';
            this.txt_SignUpPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_SignUpPassword.PlaceholderText = "Enter password";
            this.txt_SignUpPassword.ReadOnly = false;
            this.txt_SignUpPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_SignUpPassword.SelectedText = "";
            this.txt_SignUpPassword.SelectionLength = 0;
            this.txt_SignUpPassword.SelectionStart = 0;
            this.txt_SignUpPassword.ShortcutsEnabled = true;
            this.txt_SignUpPassword.Size = new System.Drawing.Size(413, 44);
            this.txt_SignUpPassword.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txt_SignUpPassword.TabIndex = 15;
            this.txt_SignUpPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_SignUpPassword.TextMarginBottom = 0;
            this.txt_SignUpPassword.TextMarginLeft = 5;
            this.txt_SignUpPassword.TextMarginTop = 0;
            this.txt_SignUpPassword.TextPlaceholder = "Enter password";
            this.txt_SignUpPassword.UseSystemPasswordChar = false;
            this.txt_SignUpPassword.WordWrap = true;
            this.txt_SignUpPassword.KeyUp += new System.Windows.Forms.KeyEventHandler(this.txt_SignUpPassword_KeyUp);
            // 
            // btn_SignUp
            // 
            this.btn_SignUp.AllowToggling = false;
            this.btn_SignUp.AnimationSpeed = 200;
            this.btn_SignUp.AutoGenerateColors = false;
            this.btn_SignUp.BackColor = System.Drawing.Color.Transparent;
            this.btn_SignUp.BackColor1 = System.Drawing.Color.Transparent;
            this.btn_SignUp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_SignUp.BackgroundImage")));
            this.btn_SignUp.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_SignUp.ButtonText = "SIGN UP";
            this.btn_SignUp.ButtonTextMarginLeft = 0;
            this.btn_SignUp.ColorContrastOnClick = 45;
            this.btn_SignUp.ColorContrastOnHover = 45;
            this.btn_SignUp.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn_SignUp.CustomizableEdges = borderEdges2;
            this.btn_SignUp.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_SignUp.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btn_SignUp.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_SignUp.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_SignUp.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_SignUp.Font = new System.Drawing.Font("Montserrat SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btn_SignUp.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(213)))), ((int)(((byte)(237)))));
            this.btn_SignUp.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_SignUp.IconMarginLeft = 11;
            this.btn_SignUp.IconPadding = 10;
            this.btn_SignUp.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btn_SignUp.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(213)))), ((int)(((byte)(237)))));
            this.btn_SignUp.IdleBorderRadius = 35;
            this.btn_SignUp.IdleBorderThickness = 2;
            this.btn_SignUp.IdleFillColor = System.Drawing.Color.Transparent;
            this.btn_SignUp.IdleIconLeftImage = null;
            this.btn_SignUp.IdleIconRightImage = null;
            this.btn_SignUp.IndicateFocus = false;
            this.btn_SignUp.Location = new System.Drawing.Point(300, 425);
            this.btn_SignUp.Name = "btn_SignUp";
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(213)))), ((int)(((byte)(237)))));
            stateProperties19.BorderRadius = 35;
            stateProperties19.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties19.BorderThickness = 2;
            stateProperties19.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(213)))), ((int)(((byte)(237)))));
            stateProperties19.ForeColor = System.Drawing.Color.White;
            stateProperties19.IconLeftImage = null;
            stateProperties19.IconRightImage = null;
            this.btn_SignUp.onHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(213)))), ((int)(((byte)(237)))));
            stateProperties20.BorderRadius = 35;
            stateProperties20.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties20.BorderThickness = 2;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(213)))), ((int)(((byte)(237)))));
            stateProperties20.IconLeftImage = null;
            stateProperties20.IconRightImage = null;
            this.btn_SignUp.OnPressedState = stateProperties20;
            this.btn_SignUp.Size = new System.Drawing.Size(166, 45);
            this.btn_SignUp.TabIndex = 10;
            this.btn_SignUp.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_SignUp.TextMarginLeft = 0;
            this.btn_SignUp.UseDefaultRadiusAndThickness = true;
            this.btn_SignUp.Click += new System.EventHandler(this.btn_SignUp_Click);
            // 
            // txt_SignUpEmail
            // 
            this.txt_SignUpEmail.AcceptsReturn = false;
            this.txt_SignUpEmail.AcceptsTab = false;
            this.txt_SignUpEmail.AnimationSpeed = 200;
            this.txt_SignUpEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_SignUpEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_SignUpEmail.BackColor = System.Drawing.Color.Transparent;
            this.txt_SignUpEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_SignUpEmail.BackgroundImage")));
            this.txt_SignUpEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_SignUpEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txt_SignUpEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_SignUpEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_SignUpEmail.BorderRadius = 1;
            this.txt_SignUpEmail.BorderThickness = 1;
            this.txt_SignUpEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_SignUpEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SignUpEmail.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txt_SignUpEmail.DefaultText = "";
            this.txt_SignUpEmail.FillColor = System.Drawing.Color.White;
            this.txt_SignUpEmail.HideSelection = true;
            this.txt_SignUpEmail.IconLeft = ((System.Drawing.Image)(resources.GetObject("txt_SignUpEmail.IconLeft")));
            this.txt_SignUpEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SignUpEmail.IconPadding = 10;
            this.txt_SignUpEmail.IconRight = null;
            this.txt_SignUpEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SignUpEmail.Lines = new string[0];
            this.txt_SignUpEmail.Location = new System.Drawing.Point(53, 207);
            this.txt_SignUpEmail.MaxLength = 32767;
            this.txt_SignUpEmail.MinimumSize = new System.Drawing.Size(100, 35);
            this.txt_SignUpEmail.Modified = false;
            this.txt_SignUpEmail.Multiline = false;
            this.txt_SignUpEmail.Name = "txt_SignUpEmail";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SignUpEmail.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.Empty;
            stateProperties22.FillColor = System.Drawing.Color.White;
            stateProperties22.ForeColor = System.Drawing.Color.Empty;
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_SignUpEmail.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SignUpEmail.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SignUpEmail.OnIdleState = stateProperties24;
            this.txt_SignUpEmail.PasswordChar = '\0';
            this.txt_SignUpEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_SignUpEmail.PlaceholderText = "Enter email";
            this.txt_SignUpEmail.ReadOnly = false;
            this.txt_SignUpEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_SignUpEmail.SelectedText = "";
            this.txt_SignUpEmail.SelectionLength = 0;
            this.txt_SignUpEmail.SelectionStart = 0;
            this.txt_SignUpEmail.ShortcutsEnabled = true;
            this.txt_SignUpEmail.Size = new System.Drawing.Size(413, 44);
            this.txt_SignUpEmail.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txt_SignUpEmail.TabIndex = 13;
            this.txt_SignUpEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_SignUpEmail.TextMarginBottom = 0;
            this.txt_SignUpEmail.TextMarginLeft = 5;
            this.txt_SignUpEmail.TextMarginTop = 0;
            this.txt_SignUpEmail.TextPlaceholder = "Enter email";
            this.txt_SignUpEmail.UseSystemPasswordChar = false;
            this.txt_SignUpEmail.WordWrap = true;
            // 
            // txt_SignUpName
            // 
            this.txt_SignUpName.AcceptsReturn = false;
            this.txt_SignUpName.AcceptsTab = false;
            this.txt_SignUpName.AnimationSpeed = 200;
            this.txt_SignUpName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_SignUpName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_SignUpName.BackColor = System.Drawing.Color.Transparent;
            this.txt_SignUpName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_SignUpName.BackgroundImage")));
            this.txt_SignUpName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_SignUpName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.txt_SignUpName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_SignUpName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txt_SignUpName.BorderRadius = 1;
            this.txt_SignUpName.BorderThickness = 1;
            this.txt_SignUpName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_SignUpName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SignUpName.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.txt_SignUpName.DefaultText = "";
            this.txt_SignUpName.FillColor = System.Drawing.Color.White;
            this.txt_SignUpName.HideSelection = true;
            this.txt_SignUpName.IconLeft = ((System.Drawing.Image)(resources.GetObject("txt_SignUpName.IconLeft")));
            this.txt_SignUpName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SignUpName.IconPadding = 10;
            this.txt_SignUpName.IconRight = null;
            this.txt_SignUpName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_SignUpName.Lines = new string[0];
            this.txt_SignUpName.Location = new System.Drawing.Point(53, 133);
            this.txt_SignUpName.MaxLength = 32767;
            this.txt_SignUpName.MinimumSize = new System.Drawing.Size(100, 35);
            this.txt_SignUpName.Modified = false;
            this.txt_SignUpName.Multiline = false;
            this.txt_SignUpName.Name = "txt_SignUpName";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SignUpName.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.Empty;
            stateProperties26.FillColor = System.Drawing.Color.White;
            stateProperties26.ForeColor = System.Drawing.Color.Empty;
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_SignUpName.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SignUpName.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_SignUpName.OnIdleState = stateProperties28;
            this.txt_SignUpName.PasswordChar = '\0';
            this.txt_SignUpName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_SignUpName.PlaceholderText = "Enter name";
            this.txt_SignUpName.ReadOnly = false;
            this.txt_SignUpName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_SignUpName.SelectedText = "";
            this.txt_SignUpName.SelectionLength = 0;
            this.txt_SignUpName.SelectionStart = 0;
            this.txt_SignUpName.ShortcutsEnabled = true;
            this.txt_SignUpName.Size = new System.Drawing.Size(413, 44);
            this.txt_SignUpName.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.txt_SignUpName.TabIndex = 12;
            this.txt_SignUpName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_SignUpName.TextMarginBottom = 0;
            this.txt_SignUpName.TextMarginLeft = 5;
            this.txt_SignUpName.TextMarginTop = 0;
            this.txt_SignUpName.TextPlaceholder = "Enter name";
            this.txt_SignUpName.UseSystemPasswordChar = false;
            this.txt_SignUpName.WordWrap = true;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Font = new System.Drawing.Font("Montserrat", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(213)))), ((int)(((byte)(237)))));
            this.label4.Location = new System.Drawing.Point(97, 35);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(327, 44);
            this.label4.TabIndex = 11;
            this.label4.Text = "Create an account";
            this.label4.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // Login
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(988, 544);
            this.Controls.Add(this.LoginPages);
            this.Controls.Add(this.LoginGradientPanel);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Login";
            this.Text = "Login";
            this.LoginGradientPanel.ResumeLayout(false);
            this.LoginGradientPanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.LoginPages.ResumeLayout(false);
            this.SignIn.ResumeLayout(false);
            this.SignIn.PerformLayout();
            this.SignUp.ResumeLayout(false);
            this.SignUp.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuFormDock LoginDock;
        private Bunifu.Framework.UI.BunifuGradientPanel LoginGradientPanel;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_SignUpPage;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_SignInPage;
        private Bunifu.UI.WinForms.BunifuPages LoginPages;
        private System.Windows.Forms.TabPage SignIn;
        private System.Windows.Forms.TabPage SignUp;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txt_SignInPassword;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txt_SignInEmail;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_SignIn;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txt_SignUpConfirmPassword;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txt_SignUpPassword;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_SignUp;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txt_SignUpEmail;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox txt_SignUpName;
        private System.Windows.Forms.Label label4;
    }
}